displayName=Voiced Dialogue
author=Graham Bartley
support=https://github.com/grabartley/runelite-voiced-dialogue
description=Voices NPC and player dialogue using local or cloud text-to-speech.
tags=tts,voice,dialogue,audio,immersion,accessibility,npc,speech,talk,text-to-speech
plugins=com.grahambartley.VoicedDialoguePlugin
version=0.1.0
build=standard
